const alumnos = [
    {
        id: 0,
        nombre: "Coronel, Ariadna de los Angeles",
        nota1: 5,
        nota2: 7,
        nota3: 8,
    },
    {
        id: 1,
        nombre: "Ruiz, Camila Florencia",
        nota1: 4,
        nota2: 3,
        nota3: 6,
    },
    {
        id: 2,
        nombre: "Carabajal, Valentina del Valle",
        nota1: 5,
        nota2: 3,
        nota3: 5,
    },
    {
        id: 3,
        nombre: "Gonzales, Luis Esteban",
        nota1: 4,
        nota2: 6,
        nota3: 8,
    },
    {
        id: 4,
        nombre: "Gonzales, Camila Luna",
        nota1: 4,
        nota2: 7,
        nota3: 3,
    },
    {
        id: 5,
        nombre: "Perez, Romina",
        nota1: 10,
        nota2: 7,
        nota3: 8,
    },
    {
        id: 6,
        nombre: "Sandoval, Lucas Gaston",
        nota1: 4,
        nota2: 3,
        nota3: 5,
    },
    {
        id: 7,
        nombre: "Giobellina, Mauricio Agustin",
        nota1: 7,
        nota2: 9,
        nota3: 8,
    },
    {
        id: 8,
        nombre: "Fernandez, Gabriela Sofia",
        nota1: 3,
        nota2: 4,
        nota3: 7,
    },
    {
        id: 9,
        nombre: "Gomez, Ezequiel Alejandro",
        nota1: 4,
        nota2: 2,
        nota3: 8,
    },
    {
        id: 10,
        nombre: "Santucho, Rodrigo Agustin",
        nota1: 6,
        nota2: 10,
        nota3: 8,
    },
]
